id = "cyan-light-theme-v2"
name = "Cyan Light Theme 2"
version = "0.1.0"
schema_version = 1
authors = ["Michał Matczuk"]
description = "Port of the Cyan Light Theme from the JetBrains"
repository = "https://github.com/mmatczuk/cyan-light-theme-zed"
